<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\MagazineCreator;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class MagazineCreatorTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_magazinecreators';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'magcreatorid',
            'creatorid',
            'magazineid',
            'creditid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'magcreatorid' => (object) [
                'name' => 'magcreatorid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'creatorid' => (object) [
                'name' => 'creatorid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'magazineid' => (object) [
                'name' => 'magazineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'creditid' => (object) [
                'name' => 'creditid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'magcreatorid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'magcreatorid' => '0',
            'creatorid' => '0',
            'magazineid' => '0',
            'creditid' => '0',
        ];
    }
}
