<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\FictionBook;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class FictionBookTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'fiction_books';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'fiction_book_id',
            'title',
            'game_line_id',
            'publisher_id',
            'product_code',
            'isbn',
            'page_count',
            'copyright',
            'url',
            'image',
            'notes',
            'rpg_shop_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'fiction_book_id' => (object) [
                'name' => 'fiction_book_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'publisher_id' => (object) [
                'name' => 'publisher_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'product_code' => (object) [
                'name' => 'product_code',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'isbn' => (object) [
                'name' => 'isbn',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'page_count' => (object) [
                'name' => 'page_count',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'copyright' => (object) [
                'name' => 'copyright',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'image' => (object) [
                'name' => 'image',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'notes' => (object) [
                'name' => 'notes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'rpg_shop_id' => (object) [
                'name' => 'rpg_shop_id',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'fiction_book_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'fiction_book_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'fiction_book_id' => null,
            'title' => '',
            'game_line_id' => null,
            'publisher_id' => null,
            'product_code' => '',
            'isbn' => '',
            'page_count' => '',
            'copyright' => '0',
            'url' => '',
            'image' => '',
            'notes' => null,
            'rpg_shop_id' => '',
        ];
    }
}
