<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\ReleaseMonth;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ReleaseMonthTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'release_months';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'release_month_id',
            'month',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'release_month_id' => (object) [
                'name' => 'release_month_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'month' => (object) [
                'name' => 'month',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'release_month_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'release_month_id' => null,
            'month' => '',
        ];
    }
}
