<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\ComicSpecialCreator;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ComicSpecialCreatorTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_comicspecialcreators';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'comicspecialcreatorid',
            'comicspecialid',
            'creatorid',
            'creditid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'comicspecialcreatorid' => (object) [
                'name' => 'comicspecialcreatorid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'comicspecialid' => (object) [
                'name' => 'comicspecialid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'creatorid' => (object) [
                'name' => 'creatorid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'creditid' => (object) [
                'name' => 'creditid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'comicspecialcreatorid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'comicspecialcreatorid' => '0',
            'comicspecialid' => '0',
            'creatorid' => '0',
            'creditid' => '0',
        ];
    }
}
