<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\OtherGame;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class OtherGameTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_other_games';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'othergameid',
            'gametitle',
            'gamelineid',
            'gametypeid',
            'publisherid',
            'productcode',
            'isbn',
            'pagecount',
            'copyright',
            'gameurl',
            'image',
            'gamenotes',
            'rpgshopid',
            'submitter',
            'imagesubmitter',
            'keywords',
            'monthid',
            'price',
            'shipdate',
            'incomplete',
            'gameupdated',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'othergameid' => (object) [
                'name' => 'othergameid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'gametitle' => (object) [
                'name' => 'gametitle',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'gamelineid' => (object) [
                'name' => 'gamelineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'gametypeid' => (object) [
                'name' => 'gametypeid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisherid' => (object) [
                'name' => 'publisherid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'productcode' => (object) [
                'name' => 'productcode',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'isbn' => (object) [
                'name' => 'isbn',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'pagecount' => (object) [
                'name' => 'pagecount',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'copyright' => (object) [
                'name' => 'copyright',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'gameurl' => (object) [
                'name' => 'gameurl',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'image' => (object) [
                'name' => 'image',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'gamenotes' => (object) [
                'name' => 'gamenotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'rpgshopid' => (object) [
                'name' => 'rpgshopid',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'submitter' => (object) [
                'name' => 'submitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'imagesubmitter' => (object) [
                'name' => 'imagesubmitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'keywords' => (object) [
                'name' => 'keywords',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'monthid' => (object) [
                'name' => 'monthid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'price' => (object) [
                'name' => 'price',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'shipdate' => (object) [
                'name' => 'shipdate',
                'type' => 'date',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => '0000-00-00',
                'autoinc' => false,
                'primary' => false,
            ],
            'incomplete' => (object) [
                'name' => 'incomplete',
                'type' => 'tinyint',
                'size' => 2,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'gameupdated' => (object) [
                'name' => 'gameupdated',
                'type' => 'date',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => '0000-00-00',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'othergameid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'othergameid' => '0',
            'gametitle' => '',
            'gamelineid' => '0',
            'gametypeid' => '0',
            'publisherid' => '0',
            'productcode' => '',
            'isbn' => '',
            'pagecount' => '',
            'copyright' => '0',
            'gameurl' => '',
            'image' => '',
            'gamenotes' => null,
            'rpgshopid' => '',
            'submitter' => '0',
            'imagesubmitter' => '0',
            'keywords' => '',
            'monthid' => '0',
            'price' => '',
            'shipdate' => '0000-00-00',
            'incomplete' => '0',
            'gameupdated' => '0000-00-00',
        ];
    }
}
