<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\PublisherLine;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class PublisherLineTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'publisher_lines';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'publisher_line_id',
            'publisher_id',
            'game_line_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'publisher_line_id' => (object) [
                'name' => 'publisher_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'publisher_id' => (object) [
                'name' => 'publisher_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'publisher_line_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'publisher_line_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'publisher_line_id' => null,
            'publisher_id' => null,
            'game_line_id' => null,
        ];
    }
}
