<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\Creator;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class CreatorTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'creators';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'creator_id',
            'first_name',
            'last_name',
            'url',
            'email',
            'notes',
            'photo',
            'birth',
            'death',
            'hometown',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'creator_id' => (object) [
                'name' => 'creator_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'first_name' => (object) [
                'name' => 'first_name',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'last_name' => (object) [
                'name' => 'last_name',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'email' => (object) [
                'name' => 'email',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'notes' => (object) [
                'name' => 'notes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'photo' => (object) [
                'name' => 'photo',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'birth' => (object) [
                'name' => 'birth',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'death' => (object) [
                'name' => 'death',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'hometown' => (object) [
                'name' => 'hometown',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'creator_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'creator_id' => null,
            'first_name' => '',
            'last_name' => '',
            'url' => '',
            'email' => '',
            'notes' => null,
            'photo' => '',
            'birth' => '',
            'death' => '',
            'hometown' => '',
        ];
    }
}
