<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\Creator;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class CreatorTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_creators';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'creatorid',
            'firstname',
            'lastname',
            'url',
            'email',
            'creatornotes',
            'photo',
            'birth',
            'death',
            'hometown',
            'updated',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'creatorid' => (object) [
                'name' => 'creatorid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'firstname' => (object) [
                'name' => 'firstname',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'lastname' => (object) [
                'name' => 'lastname',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'email' => (object) [
                'name' => 'email',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'creatornotes' => (object) [
                'name' => 'creatornotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'photo' => (object) [
                'name' => 'photo',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'birth' => (object) [
                'name' => 'birth',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'death' => (object) [
                'name' => 'death',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'hometown' => (object) [
                'name' => 'hometown',
                'type' => 'varchar',
                'size' => 250,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'updated' => (object) [
                'name' => 'updated',
                'type' => 'date',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => '0000-00-00',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'creatorid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'creatorid' => '0',
            'firstname' => '',
            'lastname' => '',
            'url' => '',
            'email' => '',
            'creatornotes' => null,
            'photo' => '',
            'birth' => '',
            'death' => '',
            'hometown' => '',
            'updated' => '0000-00-00',
        ];
    }
}
