<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\ShortStory;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ShortStoryTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'short_stories';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'short_story_id',
            'title',
            'game_line_id',
            'fiction_book_id',
            'magazine_issue_id',
            'rpg_book_id',
            'page',
            'url',
            'notes',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'short_story_id' => (object) [
                'name' => 'short_story_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'fiction_book_id' => (object) [
                'name' => 'fiction_book_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'magazine_issue_id' => (object) [
                'name' => 'magazine_issue_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'rpg_book_id' => (object) [
                'name' => 'rpg_book_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'page' => (object) [
                'name' => 'page',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'notes' => (object) [
                'name' => 'notes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'short_story_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'short_story_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'short_story_id' => null,
            'title' => '',
            'game_line_id' => null,
            'fiction_book_id' => null,
            'magazine_issue_id' => null,
            'rpg_book_id' => null,
            'page' => '0',
            'url' => '',
            'notes' => null,
        ];
    }
}
