<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\Credit;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class CreditTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_credits';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'creditid',
            'credit',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'creditid' => (object) [
                'name' => 'creditid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'credit' => (object) [
                'name' => 'credit',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'creditid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'creditid' => '0',
            'credit' => '',
        ];
    }
}
