<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\MagazineTitle;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class MagazineTitleTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'magazine_titles';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'magazine_title_id',
            'title',
            'notes',
            'url',
            'publisher_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'magazine_title_id' => (object) [
                'name' => 'magazine_title_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 200,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'notes' => (object) [
                'name' => 'notes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisher_id' => (object) [
                'name' => 'publisher_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'magazine_title_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'magazine_title_id' => null,
            'title' => '',
            'notes' => null,
            'url' => '',
            'publisher_id' => null,
        ];
    }
}
