<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\MagazineTitle;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class MagazineTitleTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_magazine_titles';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'magtitleid',
            'magtitle',
            'magtitlenotes',
            'magtitleurl',
            'publisherid',
            'publisherid2',
            'publisherid3',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'magtitleid' => (object) [
                'name' => 'magtitleid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'magtitle' => (object) [
                'name' => 'magtitle',
                'type' => 'varchar',
                'size' => 200,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'magtitlenotes' => (object) [
                'name' => 'magtitlenotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'magtitleurl' => (object) [
                'name' => 'magtitleurl',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisherid' => (object) [
                'name' => 'publisherid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisherid2' => (object) [
                'name' => 'publisherid2',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisherid3' => (object) [
                'name' => 'publisherid3',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'magtitleid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'magtitleid' => '0',
            'magtitle' => '',
            'magtitlenotes' => null,
            'magtitleurl' => '',
            'publisherid' => '0',
            'publisherid2' => '0',
            'publisherid3' => '0',
        ];
    }
}
