<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\RpgBook;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class RpgBookTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_books';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'rpg_book_id',
            'title',
            'game_line_id',
            'game_system_id',
            'publisher_id',
            'product_code',
            'isbn',
            'isbn13',
            'page_count',
            'copyright',
            'url',
            'image',
            'awards',
            'notes',
            'rpg_shop_id',
            'drivethru',
            'release_month_id',
            'cover_price',
            'pdf_price',
            'ship_date',
            'drivethrough_url',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'rpg_book_id' => (object) [
                'name' => 'rpg_book_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 200,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'game_system_id' => (object) [
                'name' => 'game_system_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'publisher_id' => (object) [
                'name' => 'publisher_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'product_code' => (object) [
                'name' => 'product_code',
                'type' => 'varchar',
                'size' => 20,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'isbn' => (object) [
                'name' => 'isbn',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'isbn13' => (object) [
                'name' => 'isbn13',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'page_count' => (object) [
                'name' => 'page_count',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'copyright' => (object) [
                'name' => 'copyright',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'image' => (object) [
                'name' => 'image',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'awards' => (object) [
                'name' => 'awards',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'notes' => (object) [
                'name' => 'notes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'rpg_shop_id' => (object) [
                'name' => 'rpg_shop_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'drivethru' => (object) [
                'name' => 'drivethru',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'release_month_id' => (object) [
                'name' => 'release_month_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'cover_price' => (object) [
                'name' => 'cover_price',
                'type' => 'decimal',
                'size' => 10,
                'scale' => 2,
                'notnull' => true,
                'default' => '0.00',
                'autoinc' => false,
                'primary' => false,
            ],
            'pdf_price' => (object) [
                'name' => 'pdf_price',
                'type' => 'decimal',
                'size' => 10,
                'scale' => 2,
                'notnull' => true,
                'default' => '0.00',
                'autoinc' => false,
                'primary' => false,
            ],
            'ship_date' => (object) [
                'name' => 'ship_date',
                'type' => 'date',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => '2002-01-01',
                'autoinc' => false,
                'primary' => false,
            ],
            'drivethrough_url' => (object) [
                'name' => 'drivethrough_url',
                'type' => 'varchar',
                'size' => 500,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'rpg_book_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'rpg_book_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'rpg_book_id' => null,
            'title' => '',
            'game_line_id' => null,
            'game_system_id' => null,
            'publisher_id' => null,
            'product_code' => '',
            'isbn' => '',
            'isbn13' => '',
            'page_count' => '0',
            'copyright' => '0',
            'url' => '',
            'image' => '',
            'awards' => null,
            'notes' => null,
            'rpg_shop_id' => '0',
            'drivethru' => '0',
            'release_month_id' => null,
            'cover_price' => '0.00',
            'pdf_price' => '0.00',
            'ship_date' => '2002-01-01',
            'drivethrough_url' => null,
        ];
    }
}
