<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\MagazineArticle;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class MagazineArticleTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_magazine_articles';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'articleid',
            'arttitle',
            'gamelineid',
            'magazineid',
            'page',
            'articlenotes',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'articleid' => (object) [
                'name' => 'articleid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'arttitle' => (object) [
                'name' => 'arttitle',
                'type' => 'varchar',
                'size' => 200,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'gamelineid' => (object) [
                'name' => 'gamelineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'magazineid' => (object) [
                'name' => 'magazineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'page' => (object) [
                'name' => 'page',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'articlenotes' => (object) [
                'name' => 'articlenotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'articleid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'articleid' => '0',
            'arttitle' => '',
            'gamelineid' => '0',
            'magazineid' => '0',
            'page' => '0',
            'articlenotes' => null,
        ];
    }
}
