<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\GameSystem;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GameSystemTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'game_systems';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'game_system_id',
            'game_system',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'game_system_id' => (object) [
                'name' => 'game_system_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'game_system' => (object) [
                'name' => 'game_system',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'game_system_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'game_system_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'game_system_id' => null,
            'game_system' => '',
        ];
    }
}
