<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\GameSystem;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GameSystemTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_gamesystems';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'systemid',
            'gamesystem',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'systemid' => (object) [
                'name' => 'systemid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'gamesystem' => (object) [
                'name' => 'gamesystem',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'systemid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'systemid' => '0',
            'gamesystem' => '',
        ];
    }
}
