<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\ComicTitle;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ComicTitleTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'comic_titles';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'comic_title_id',
            'title',
            'publisher_id',
            'game_line_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'comic_title_id' => (object) [
                'name' => 'comic_title_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'publisher_id' => (object) [
                'name' => 'publisher_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'comic_title_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'comic_title_id' => null,
            'title' => '',
            'publisher_id' => null,
            'game_line_id' => null,
        ];
    }
}
