<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\GameType;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GameTypeTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'game_types';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'game_type_id',
            'game_type',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'game_type_id' => (object) [
                'name' => 'game_type_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'game_type' => (object) [
                'name' => 'game_type',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'game_type_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'game_type_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'game_type_id' => null,
            'game_type' => '',
        ];
    }
}
