<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\GameType;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GameTypeTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_gametypes';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'gametypeid',
            'gametype',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'gametypeid' => (object) [
                'name' => 'gametypeid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'gametype' => (object) [
                'name' => 'gametype',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'gametypeid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'gametypeid' => '0',
            'gametype' => '',
        ];
    }
}
