<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\GameLine;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GameLineTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'game_lines';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'game_line_id',
            'game_line',
            'genre',
            'keywords',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'game_line_id' => (object) [
                'name' => 'game_line_id',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'game_line' => (object) [
                'name' => 'game_line',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'genre' => (object) [
                'name' => 'genre',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'keywords' => (object) [
                'name' => 'keywords',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'game_line_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'game_line_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'game_line_id' => null,
            'game_line' => '',
            'genre' => '',
            'keywords' => '',
        ];
    }
}
