<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\Magazine;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class MagazineTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_magazines';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'magazineid',
            'magtitleid',
            'issuenumber',
            'coverdate',
            'pagecount',
            'magazinenotes',
            'magcover',
            'magazineurl',
            'submitter',
            'imagesubmitter',
            'incomplete',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'magazineid' => (object) [
                'name' => 'magazineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'magtitleid' => (object) [
                'name' => 'magtitleid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'issuenumber' => (object) [
                'name' => 'issuenumber',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'coverdate' => (object) [
                'name' => 'coverdate',
                'type' => 'varchar',
                'size' => 100,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'pagecount' => (object) [
                'name' => 'pagecount',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'magazinenotes' => (object) [
                'name' => 'magazinenotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'magcover' => (object) [
                'name' => 'magcover',
                'type' => 'varchar',
                'size' => 50,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'magazineurl' => (object) [
                'name' => 'magazineurl',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'submitter' => (object) [
                'name' => 'submitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'imagesubmitter' => (object) [
                'name' => 'imagesubmitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'incomplete' => (object) [
                'name' => 'incomplete',
                'type' => 'tinyint',
                'size' => 2,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'magazineid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'magazineid' => '0',
            'magtitleid' => '0',
            'issuenumber' => '0',
            'coverdate' => '',
            'pagecount' => '0',
            'magazinenotes' => null,
            'magcover' => '',
            'magazineurl' => '',
            'submitter' => '0',
            'imagesubmitter' => '0',
            'incomplete' => '0',
        ];
    }
}
