<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\ShortFiction;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ShortFictionTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_shortfiction';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'shortfictionid',
            'shortfictiontitle',
            'gamelineid',
            'fictionid',
            'magazineid',
            'bookid',
            'page',
            'url',
            'shortfictionnotes',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'shortfictionid' => (object) [
                'name' => 'shortfictionid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'shortfictiontitle' => (object) [
                'name' => 'shortfictiontitle',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'gamelineid' => (object) [
                'name' => 'gamelineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'fictionid' => (object) [
                'name' => 'fictionid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'magazineid' => (object) [
                'name' => 'magazineid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'bookid' => (object) [
                'name' => 'bookid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'page' => (object) [
                'name' => 'page',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'shortfictionnotes' => (object) [
                'name' => 'shortfictionnotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'shortfictionid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'shortfictionid' => '0',
            'shortfictiontitle' => '',
            'gamelineid' => '0',
            'fictionid' => '0',
            'magazineid' => '0',
            'bookid' => '0',
            'page' => '0',
            'url' => '',
            'shortfictionnotes' => null,
        ];
    }
}
