<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace PenPaper\Persistence\DataSource\Comic;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class ComicTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'rpg_comics';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'comicid',
            'comictitleid',
            'issuenumber',
            'coverdate',
            'pagecount',
            'comicnotes',
            'comiccover',
            'comicurl',
            'submitter',
            'imagesubmitter',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'comicid' => (object) [
                'name' => 'comicid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => true,
            ],
            'comictitleid' => (object) [
                'name' => 'comictitleid',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'issuenumber' => (object) [
                'name' => 'issuenumber',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'coverdate' => (object) [
                'name' => 'coverdate',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'pagecount' => (object) [
                'name' => 'pagecount',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'comicnotes' => (object) [
                'name' => 'comicnotes',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'comiccover' => (object) [
                'name' => 'comiccover',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'comicurl' => (object) [
                'name' => 'comicurl',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => true,
                'default' => '',
                'autoinc' => false,
                'primary' => false,
            ],
            'submitter' => (object) [
                'name' => 'submitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
            'imagesubmitter' => (object) [
                'name' => 'imagesubmitter',
                'type' => 'int',
                'size' => 11,
                'scale' => null,
                'notnull' => true,
                'default' => '0',
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'comicid',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'comicid' => '0',
            'comictitleid' => '0',
            'issuenumber' => '0',
            'coverdate' => '',
            'pagecount' => '0',
            'comicnotes' => null,
            'comiccover' => '',
            'comicurl' => '',
            'submitter' => '0',
            'imagesubmitter' => '0',
        ];
    }
}
